create table
  public.feedback_messages (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    user_id uuid not null,
    context text not null,
    message text not null,
    constraint feedback_messages_pkey primary key (id),
    constraint feedback_messages_user_id_fkey foreign key (user_id) references profiles (id)
  ) tablespace pg_default;

create trigger "NotifyAdminFeedback"
after insert on feedback_messages for each row
execute function supabase_functions.http_request (
  'https://worldofnuclear.com/api/admin/notify/feedback',
  'POST',
  '{"Content-type":"application/json"}',
  '{}',
  '1000'
);