create table
  public.events (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    actor uuid null,
    details json null,
    constraint events_pkey primary key (id)
  ) tablespace pg_default;