/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Achievements {
  description: string | null;
  id: Generated<number>;
  karma_value: Generated<number>;
  name: string;
}

export interface FluxBoosts {
  created_at: Generated<Timestamp>;
  flux_id: number;
  flux_user_id: number;
}

export interface Fluxes {
  blargy: string | null;
  boost_count: Generated<number>;
  content: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  flux_user_id: number;
  id: Generated<number>;
  parent_id: number | null;
  reply_count: Generated<number>;
  updated_at: Generated<Timestamp>;
  view_count: Generated<number>;
}

export interface FluxFollowers {
  created_at: Generated<Timestamp>;
  follower_id: number;
  following_id: number;
}

export interface FluxUsers {
  created_at: Generated<Timestamp>;
  digest_frequency: string | null;
  display_name: string;
  email_notifications: Timestamp | null;
  handle: string;
  id: Generated<number>;
  text_notifications: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface FluxViews {
  created_at: Generated<Timestamp>;
  flux_id: number;
  flux_user_id: number | null;
}

export interface Identities {
  access_token: string;
  created_at: Generated<Timestamp>;
  email: Generated<string>;
  id: Generated<string>;
  identity_data: Json;
  last_sign_in_at: Timestamp;
  provider: string;
  provider_id: string;
  refresh_token: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface KarmaAwards {
  achievement_id: number | null;
  created_at: Generated<Timestamp>;
  flux_user_id: number;
  karma_awarded: Generated<number>;
  name: string;
}

export interface MagicAuth {
  alias: string | null;
  email: string;
  expires_at: Timestamp;
  failed_validation_at: Timestamp | null;
  id: Generated<number>;
  token: string;
  verified_at: Timestamp | null;
}

export interface Profiles {
  avatar_url: string | null;
  bio: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  email_verified_at: Timestamp | null;
  full_name: string | null;
  id: Generated<string>;
  join_reason: string | null;
  karma_score: Generated<number>;
  location: string | null;
  nuclear_likes: string | null;
  screen_name: string | null;
  updated_at: Generated<Timestamp>;
  website: string | null;
  x_username: string | null;
}

export interface Users {
  alias: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  last_sign_in_at: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  achievements: Achievements;
  flux_boosts: FluxBoosts;
  flux_followers: FluxFollowers;
  flux_users: FluxUsers;
  flux_views: FluxViews;
  fluxes: Fluxes;
  identities: Identities;
  karma_awards: KarmaAwards;
  magic_auth: MagicAuth;
  profiles: Profiles;
  users: Users;
}
