/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Achievements {
  description: string | null;
  id: Generated<number>;
  karma_value: Generated<number>;
  name: string;
}

export interface ApiKeys {
  created_at: Generated<Timestamp>;
  description: string | null;
  expires_at: Timestamp | null;
  id: Generated<number>;
  key_hash: string;
  last_used_at: Timestamp | null;
  revoked_at: Timestamp | null;
  user_id: string;
}

export interface Courses {
  archived_at: Timestamp | null;
  cover_art: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  public_key: string;
  published_at: Timestamp | null;
  syllabus: string | null;
  teaser: string | null;
  test_only: boolean | null;
  title: string | null;
}

export interface Events {
  actor_id: string | null;
  created_at: Generated<Timestamp>;
  details: Json;
  id: Generated<number>;
}

export interface FeedbackMessages {
  context: Json;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  message: string;
  user_id: string | null;
}

export interface FluxBoosts {
  boosted_at: Generated<Timestamp>;
  flux_id: number;
  flux_user_id: number;
}

export interface Fluxes {
  author_id: number;
  blocked_at: Timestamp | null;
  boosts: Generated<number>;
  content: string;
  deleted_at: Timestamp | null;
  id: Generated<number>;
  posted_at: Generated<Timestamp>;
  reaction_to: number | null;
  reactions: Generated<number>;
  updated_at: Generated<Timestamp>;
  views: Generated<number>;
}

export interface FluxFollowers {
  followed_at: Generated<Timestamp>;
  follower_id: number;
  following_id: number;
}

export interface FluxRatingLevels {
  code: string;
  created_at: Generated<Timestamp>;
  description: string;
  display: string | null;
  retired: Timestamp | null;
  severity: number | null;
}

export interface FluxRatings {
  action_taken: string | null;
  created_at: Generated<Timestamp>;
  flux_id: Generated<number>;
  id: Generated<number>;
  moderator_id: string;
  rating: Generated<string>;
  reason: string | null;
  review_note: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
}

export interface FluxUsers {
  created_at: Generated<Timestamp>;
  followers: Generated<number>;
  following: Generated<number>;
  id: Generated<number>;
  user_id: string;
}

export interface FluxViews {
  flux_id: number;
  flux_user_id: number | null;
  viewed_at: Generated<Timestamp>;
}

export interface Identities {
  access_token: string;
  created_at: Generated<Timestamp>;
  email: Generated<string>;
  id: Generated<string>;
  identity_data: Json;
  last_sign_in_at: Timestamp;
  provider: string;
  provider_id: string;
  refresh_token: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Invitations {
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  delivery_error: string | null;
  id: Generated<number>;
  invitee_email: string;
  invitee_name: string;
  joined_at: Timestamp | null;
  joined_user_id: string | null;
  referral_code: string;
  referred_by_id: string;
  sent_at: Timestamp | null;
  target_feature: string | null;
  unsubscribed_at: Timestamp | null;
}

export interface KarmaAwards {
  achievement_id: number | null;
  created_at: Generated<Timestamp>;
  karma_awarded: Generated<number>;
  name: string;
  user_id: string;
}

export interface LearningBookmarks {
  id: Generated<number>;
  lesson_key: string;
  path_key: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface LessonContentParts {
  content: Json;
  id: Generated<number>;
  lesson_content_type: string;
  lesson_key: string;
  public_key: string;
  sequence: number | null;
}

export interface LessonPaths {
  course_key: string | null;
  description: string | null;
  id: Generated<number>;
  name: string | null;
  public_key: string | null;
  trailhead: string | null;
}

export interface LessonPlans {
  archived_at: Timestamp | null;
  course_key: string | null;
  cover_art: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  objective: string | null;
  public_key: string;
  published_at: Timestamp | null;
  sequence: number | null;
  title: string | null;
}

export interface LessonSteps {
  from: string | null;
  id: Generated<number>;
  lesson_path: string | null;
  teaser: string | null;
  to: string | null;
}

export interface MagicAuth {
  alias: string | null;
  email: string;
  expires_at: Timestamp;
  failed_validation_at: Timestamp | null;
  id: Generated<number>;
  token: string;
  verified_at: Timestamp | null;
}

export interface ObjectionReasons {
  code: string;
  description: string;
  sort: number | null;
}

export interface Profiles {
  avatar_url: string | null;
  bio: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  join_reason: string | null;
  karma_score: Generated<number>;
  location: string | null;
  nuclear_likes: string | null;
  screen_name: string | null;
  updated_at: Generated<Timestamp>;
  website: string | null;
  x_username: string | null;
}

export interface Roles {
  created_at: Generated<Timestamp>;
  description: string | null;
  key: string;
  label: string;
  updated_at: Generated<Timestamp>;
}

export interface Unsubscribes {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
}

export interface UserProfiles {
  alias: string | null;
  avatar: string | null;
  bio: string | null;
  created_at: Generated<Timestamp>;
  full_name: string | null;
  glam_shot: string | null;
  handle: string | null;
  id: string;
  karma_score: Generated<number | null>;
  location: string | null;
  updated_at: Generated<Timestamp>;
  website: string | null;
  why_joined: string | null;
  why_nuclear: string | null;
}

export interface UserRoles {
  granted_at: Generated<Timestamp>;
  id: Generated<string>;
  role_id: string;
  user_id: string;
}

export interface Users {
  alias: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  last_sign_in_at: Timestamp;
  system_bot: Generated<boolean | null>;
  updated_at: Generated<Timestamp>;
}

export interface ViolationReports {
  app_key: string;
  content_key: string;
  created_at: Generated<Timestamp>;
  handled_at: Timestamp | null;
  handled_by: string | null;
  id: Generated<number>;
  message: string | null;
  reasons: string[];
  reported_by: string;
  resolution_note: string | null;
}

export interface DB {
  achievements: Achievements;
  api_keys: ApiKeys;
  courses: Courses;
  events: Events;
  feedback_messages: FeedbackMessages;
  flux_boosts: FluxBoosts;
  flux_followers: FluxFollowers;
  flux_rating_levels: FluxRatingLevels;
  flux_ratings: FluxRatings;
  flux_users: FluxUsers;
  flux_views: FluxViews;
  fluxes: Fluxes;
  identities: Identities;
  invitations: Invitations;
  karma_awards: KarmaAwards;
  learning_bookmarks: LearningBookmarks;
  lesson_content_parts: LessonContentParts;
  lesson_paths: LessonPaths;
  lesson_plans: LessonPlans;
  lesson_steps: LessonSteps;
  magic_auth: MagicAuth;
  objection_reasons: ObjectionReasons;
  profiles: Profiles;
  roles: Roles;
  unsubscribes: Unsubscribes;
  user_profiles: UserProfiles;
  user_roles: UserRoles;
  users: Users;
  violation_reports: ViolationReports;
}
